import type {FrameSettings} from '../types';

export const DEFAULT_SETTINGS: FrameSettings = {
  padding: 24,
  aspectRatio: 'original',
  borderRadius: 20,
  shadowSize: 5,
  shadowOpacity: 0.2,
  borderWidth: 0,
  borderColor: '#000000',
  backgroundColor: '#ffffff',
  backgroundType: 'blur',
  gradientStartColor: '#4facfe',
  gradientEndColor: '#00f2fe',
  gradientAngle: 135,
  backgroundBrightness: 100,
  blurAmount: 26,
  showExif: true,
  textColor: '#ffffff',
  infoPosition: 'bottom',
  infoLayout: 'centered',
  infoPadding: 0,
  infoGap: 4,
  infoOffset: {x: 0, y: 0},
  line1Style: {
    fontId: 'Inter',
    fontSize: 18,
    fontWeight: 700,
    letterSpacing: 0.05,
    opacity: 1,
  },
  line2Style: {
    fontId: 'Inter',
    fontSize: 14,
    fontWeight: 400,
    letterSpacing: 0.02,
    opacity: 0.7,
  },
  customExif: {},
  exportFormat: 'jpeg',
  exportQuality: 0.9,
  exportScale: 4,
};
